### ISSUE TITLE
Incorrect character encoding

### ISSUE THREAD

**Issue by dnicolson** [gignupg/Detect-File-Encoding-And-Language#11]
Character encoding detection is wholly based on the language detected (if not already detected as `UTF-8`), and in many cases this defaults to `CP1252` character encoding.

The Google homepage served in Germany is unable to be detected:

```
dfeal google-de.html
{
    "encoding": null,
    "language": null,
    "confidence": {
        "encoding": null,
        "language": null
    }
}
```

The content is actually encoded in the `ISO-8859-1` character set (the meta charset value is `UTF-8` but that's a different issue):
```
file google-de.html
google-de.html: HTML document text, ISO-8859 text, with very long lines (2439)
```

Adding " das " (https://github.com/gignupg/Detect-File-Encoding-And-Language/blob/063340d/src/config/languageObject.js#L13) to the file allows the language to be detected as German but the character encoding comes from https://github.com/gignupg/Detect-File-Encoding-And-Language/blob/063340d/src/config/languageObject.js#L198 which is incorrect:
```
echo " das " | cat - google-de.html > google-de-with-das.html
dfeal google-de-with-das.html
{
    "encoding": "CP1252",
    "language": "german",
    "confidence": {
        "encoding": 0.03,
        "language": 0.03
    }
}
```

The Google homepage served in the US is encoded in `ASCII` but is detected as `UTF-8`:
```
file google-us.html
google-us.html: HTML document text, ASCII text, with very long lines (2442)
dfeal google-us.html
{
    "encoding": "UTF-8",
    "language": "english",
    "confidence": {
        "encoding": 1,
        "language": 0.03
    }
}
```

The character encoding should be detected independently of the language, maybe an npm package could be used? Based on https://github.com/file/file/blob/master/src/encoding.c, detecting the character encoding is not trivial.

[google-us.html.zip](https://github.com/gignupg/Detect-File-Encoding-And-Language/files/10892490/google-us.html.zip)
[google-de.html.zip](https://github.com/gignupg/Detect-File-Encoding-And-Language/files/10892489/google-de.html.zip)

**Comment by gignupg** [comment]
Hey @dnicolson, thx so much for your very detailed report! 
It's true that in many cases the encoding is based on the detected language. However, I wasn't aware that this was an issue since you can open an ASCII-encoded file with UTF-8 without any problems. If you know how to differentiate between ASCII and UTF-8 as well as CP1252 and ISO-8859-1 you're very welcome to create a PR and fix it! I'll gladly accept it!
The reason Germany's Google homepage couldn't be detected has to do with the language-detection method that's being used by this package as you've discovered already. As mentioned in the readme:

> For reliable encoding and language detection, use files containing 500 words or more. Smaller inputs can work as well but the results might be less accurate and in some cases incorrect.

What I meant by 500 words was words in coherent sentences. Not code. I should probably specify this better in the readme.

**Comment by dnicolson** [comment]
I'm not so sure that the issue is ready to be closed, the main problem of character encoding detection is still present.

I would suggest using an npm module, something like https://www.npmjs.com/package/chardet instead of deriving the character encoding from the language, which is problematic.

At the moment the character encoding is incorrectly detected for https://github.com/gignupg/Detect-File-Encoding-And-Language/blob/063340d/src/config/languageObject.js#L257-L263 and https://github.com/gignupg/Detect-File-Encoding-And-Language/blob/063340d/src/config/languageObject.js#L284-L290, neither conforms to the Windows-1252 character set.

**Comment by gignupg** [comment]
In what use case would it be "problematic" to detect UTF-8 instead of ASCII? Likewise, CP1252 instead of ISO-8859-1?

**Comment by gignupg** [comment]
Ok, I've taken a look at your links. So, you're saying there is a problem with Serbo-Croatian and Malay-Indonesion.
To me it looks like though, Serbo-Croatian can be read with Windows-1252 without any problems. Here is an extract of Harry Potter's Serbo-Croatian subtitle file read with Windows-1252:
> Mogao sam i misliti da æu vas zateæi ovdje...
Profesorice McGonagall.
Dobra veèer, profesore Dumbledore.
Jesu li glasine toène?
-Nažalost, jesu.
I one dobre... I one loše.
A djeèak?
-Hagrid æe ga dovesti.
Je li pametno tako važan
zadatak povjeriti Hagridu?
Profesorice, Hagridu bih
povjerio i vlastiti život.
Profesore Dumbledore,
profesorice McGonagall.
Nadam se da nije bilo
problema, Hagride? -Nije.
Maleni je zaspao dok
smo letjeli iznad Bristola.
Samo ga nemojte probudit.

Are there any characters that Windows-1252 is representing incorrectly here?

**Comment by dnicolson** [comment]
It's simply problematic to determine the character encoding based on the detected language, there is relatively little coupling.

According to [W3C](https://www.w3.org/International/O-charset-lang.html), Serbian does not conform to Windows-1252 (which also doesn't support Cyrillic):
```
Serbian (sr) cyrillic | windows-1251, iso-8859-5***
Serbian (sr) latin | iso-8859-2, windows-1250
```
