### ISSUE TITLE
Pass in a buffer rather than a file path

### ISSUE THREAD

**Issue by curiousdannii** [gignupg/Detect-File-Encoding-And-Language#3]
Would it be possible to pass in a buffer rather than a file path?

**Comment by gignupg** [comment]
Sure, we could add that option. I'll accept the pull request if you do one!

**Comment by gfreecs0510** [comment]
@gignupg seems like its a year old request, are you planning to support buffer/steam in the future? i tested ur work and i would say its more accurate than `chardet` package. 

I'll try to create a PR myself if i find some time

**Comment by gignupg** [comment]
@gfreecs0510 That's a huge compliment, thanks a lot!
Regarding the buffer feature, I wasn't planning on implementing it myself, but I know that a lot of people have requested it, so a PR would be very welcome!

**Comment by davuses** [comment]
You can create a blob object from the buffer and pass it as argument to the API, something like:
```js
const file= new Blob([buffer]);
languageEncoding(file).then((fileInfo) => console.log(fileInfo));
```
This should work

**Comment by gignupg** [comment]
@davuses thx for the code snippet! Would you want to implement it and do a PR? I'm a little bit busy at the moment...

**Comment by davuses** [comment]
> @davuses thx for the code snippet! Would you want to implement it and do a PR? I'm a little bit busy at the moment...

It's probably not necessary to make changes to the code, like I said above the current API can handle buffer as long as you make a blob object out of it, it's quite simple. So maybe add a snippet demo to show how this could be done in readme file.

**Comment by gignupg** [comment]
Thx @davuses for clarifying! I added a link to your code snipped in the readme and published a new version to NPM!

**Comment by erkstruwe** [comment]
> You can create a blob object from the buffer and pass it as argument to the API, something like:
> 
> ```js
> const file= new Blob([buffer]);
> languageEncoding(file).then((fileInfo) => console.log(fileInfo));
> ```
> 
> This should work

In Node.js, you need to create a temporary URL for this to work. If using @davuses' solution only, the buffer will be used as a file path most likely resulting in `ENOENT`.

```typescript
const file = URL.createObjectURL(new Blob([body]))
const fileInfo = await languageEncoding(file).finally(() => URL.revokeObjectURL(file))
```

**Comment by erkstruwe** [comment]
> You can create a blob object from the buffer and pass it as argument to the API, something like:
> 
> ```js
> const file= new Blob([buffer]);
> languageEncoding(file).then((fileInfo) => console.log(fileInfo));
> ```
> 
> This should work

This only works in the browser. I added a PR for support in Node.js: https://github.com/gignupg/Detect-File-Encoding-And-Language/pull/12.
