### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by italodeandra** [gignupg/Detect-File-Encoding-And-Language#4]
It would be great if this package had types for using with TypeScript.

**Comment by gignupg** [comment]
I completely agree! I thought about adding types multiple times but haven't had the time so far. Feel free to add types via [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). Should I have more time at some point in the future, I'll rewrite it using TypeScript!

**Comment by gignupg** [comment]
@italodeandra TypeScript is now finally supported! I just published a new version to NPM xD
