### ISSUE TITLE
Is it possible to use the result externally?

### ISSUE THREAD

**Issue by lwcorp** [gignupg/Detect-File-Encoding-And-Language#6]
I'd like to do a series of many actions based on the encoding and I don't want to run all these actions inside `then`.

So is it possible to return a value to an external variable like `the_encoding`? If so, could you update the Readme accordingly?

I know it involves a `promise`, but still thought it's worth a shot to ask.

I've tried the following which returns `undefined`:
```
document.getElementById("my-input-field").addEventListener("change", (e) => {
  var the_encoding;
  const file = e.target.files[0];
  languageEncoding(file).then((fileInfo) => the_encoding = fileInfo.encoding); // also tried this.the_encoding...
  console.log(the_encoding); // undefined...
  // Then run various actions involving the_encoding
});
```

**Comment by gignupg** [comment]
Hey there, is it possible that what you're looking for is "async/await"? 

This is how I would do it with "async/await":
```
document.getElementById("my-input-field").addEventListener("change", async (e) => {
  const file = e.target.files[0];
  const the_encoding = await languageEncoding(file);
  console.log(the_encoding);   // { language: english, encoding: UTF-8, confidence: { encoding: 1, language: 1 } }
});
```

To learn more about "async/await" here is a good tutorial: https://www.youtube.com/watch?v=V_Kr9OSfDeU

**Comment by lwcorp** [comment]
Thanks! I wasn't aware async is needed at the event function and that it's either `then` or external support.

Sent a pull request #7 to the Readme.

**Comment by gignupg** [comment]
Glad I could help!
